#include "dna.tech.leetcode.th"

namespace dna.tech.leetcode

class tools
    static method OutStd(vList as variadic) as character
end class

static function ___tools____OutStd(vList as variadic) as character

    local cOut:="",cValType as character

    local nIdx as numeric

    local jJSON as json

    local uValue as variant

    begin sequence

        if (vList==nil)
            break
        endif

        for nIdx:=1 to vList:vCount
            uValue:=vList:vArgs[nIdx]
            cValType:=ValType(uValue)
            if (cValType=="A")
                jJSON:=JSONObject():New()
                jJSON:Set(uValue)
                cOut+=jJSON:ToJSON()
                freeObj(@jJSON)
            elseif (cValType=="N")
                cOut+=hb_NToC(uValue)
            elseif (cValType=="L")
                cOut+=FWJSONSerialize(uValue)
            elseif (cValType=="J")
                cOut+=uValue:ToJSON()
            elseif (cValType!="C")
                cOut+=cValToChar(uValue)
            else
                cOut+=uValue
            endif
        next nIdx

    end sequence

    return(cOut)
